In [3]:
import numpy as np 
import pandas as pd

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

clns = ["Name","Age","City","Salary"]
df1 = pd.DataFrame(data_list, columns = clns)

In [6]:
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
df1[['Name','Salary']]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [8]:
df1["Designation"] = ["Docter","Eng.","Docter","Eng."]

In [9]:
df1

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Docter
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Docter
3  Linda   42    London   85000        Eng.

In [10]:
df1.drop("Designation",axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
df1.drop("Designation",axis=1,inplace=True)

In [12]:
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
df1.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [20]:
df1.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [22]:
df1.loc[[2,3]][["Name","Salary"]]

    Name  Salary
2  Peter   62000
3  Linda   85000

In [23]:
df1[df1["Age"] > 30 ]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [24]:
df1[(df1["Age"] > 30) & (df1["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000