In [2]:
import numpy as np 
import pandas as pd

In [30]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [31]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [32]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [33]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [34]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [35]:
df.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0

In [36]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [37]:
df.fillna(23)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  23.0
2  23.0  3   3.0  23.0
3   4.0  4  23.0  23.0
4   5.0  5  23.0   5.0

In [38]:
values = {"A": 20 , "B": 30 , "C": 40 , "D": 50}

df.fillna(value= values)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  50.0
2  20.0  3   3.0  50.0
3   4.0  4  40.0  50.0
4   5.0  5  40.0   5.0

In [39]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0