In [4]:
import numpy as np 
import pandas as pd

**Pivot Table**

In [5]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data) 
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    278     74   John  January      Q1
1  2023-01-02       B   West    691     63   Mary  January      Q1
2  2023-01-03       C  North    506     14    Bob  January      Q1
3  2023-01-04       D  South    522     41  Alice  January      Q1
4  2023-01-05       A   East    258     60   John  January      Q1
5  2023-01-06       B   West    427     45   Mary  January      Q1
6  2023-01-07       C  North    411     54    Bob  January      Q1
7  2023-01-08       D  South    910     71  Alice  January      Q1
8  2023-01-09       A   East    890     74   John  January      Q1
9  2023-01-10       B   West    415     75   Mary  January      Q1
10 2023-01-11       C  North    838     56    Bob  January      Q1
11 2023-01-12       D  South    800     57  Alice  January      Q1
12 2023-01-13       A   East    371     45   John  January      Q1
13 2023-01-14       B   West    550     55   Mary  January      Q1
14 2023-01-15       C  North    232     91    Bob  January      Q1
15 2023-01-16       D  South    180     46  Alice  January      Q1
16 2023-01-17       A   East    957     69   John  January      Q1
17 2023-01-18       B   West    440     55   Mary  January      Q1
18 2023-01-19       C  North    369     86    Bob  January      Q1
19 2023-01-20       D  South    525     17  Alice  January      Q1

In [6]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    278     74   John  January      Q1
1  2023-01-02       B   West    691     63   Mary  January      Q1
2  2023-01-03       C  North    506     14    Bob  January      Q1
3  2023-01-04       D  South    522     41  Alice  January      Q1
4  2023-01-05       A   East    258     60   John  January      Q1
5  2023-01-06       B   West    427     45   Mary  January      Q1
6  2023-01-07       C  North    411     54    Bob  January      Q1
7  2023-01-08       D  South    910     71  Alice  January      Q1
8  2023-01-09       A   East    890     74   John  January      Q1
9  2023-01-10       B   West    415     75   Mary  January      Q1
10 2023-01-11       C  North    838     56    Bob  January      Q1
11 2023-01-12       D  South    800     57  Alice  January      Q1
12 2023-01-13       A   East    371     45   John  January      Q1
13 2023-01-14       B   West    550     55   Mary  January      Q1
14 2023-01-15       C  North    232     91    Bob  January      Q1
15 2023-01-16       D  South    180     46  Alice  January      Q1
16 2023-01-17       A   East    957     69   John  January      Q1
17 2023-01-18       B   West    440     55   Mary  January      Q1
18 2023-01-19       C  North    369     86    Bob  January      Q1
19 2023-01-20       D  South    525     17  Alice  January      Q1

In [8]:
pvt1 = pd.pivot_table(df,values="Sales",index="Region",columns="Product")
pvt1

Product      A      B      C      D
Region
East     550.8    NaN    NaN    NaN
North      NaN    NaN  471.2    NaN
South      NaN    NaN    NaN  587.4
West       NaN  504.6    NaN    NaN

In [9]:
pvt2 = pd.pivot_table(df,values= ["Sales","Units"],index="Region",columns="Product")
pvt2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     550.8    NaN    NaN    NaN  64.4   NaN   NaN   NaN
North      NaN    NaN  471.2    NaN   NaN   NaN  60.2   NaN
South      NaN    NaN    NaN  587.4   NaN   NaN   NaN  46.4
West       NaN  504.6    NaN    NaN   NaN  58.6   NaN   NaN

**Cross Tabs**

In [10]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0